@startuml hidalgo2_dma
'left to right direction
skinparam actorStyle awesome

'packages

package "Data Management" << DMA >> {
    left to right direction


    usecase SCODMA001 as "
    Data Quering
    "

    usecase SCODMA002 as "
    UAP data collection
    "

    usecase SCODMA003 as "
    UBM data collection
    "

    usecase SCODMA004 as "
    RES data collection
    "

    usecase SCODMA005 as "
    WF data collection
    "

    usecase SCODMA006  as "
    Data Provisioning
    "

    usecase SCODMA007  as "
    Data Collection
    "

    usecase SCODMA008  as "
    Data Transfer
    "

    usecase SCODMA009  as "
    Data Processing (HPDA)
    "

    usecase SCODMA010  as "
    Data Monitoring (HPDA)
    "

    usecase SCODMA011  as "
    Data Visualization
    "

    SCODMA002 -d-|> SCODMA007
    SCODMA003 -d-|> SCODMA007
    SCODMA004 -d-|> SCODMA007
    SCODMA005 -d-|> SCODMA007

    
    SCODMA006 .u.> SCODMA001 : include
    SCODMA006 .u.> SCODMA007 : include
    SCODMA006 .u.> SCODMA008 : include
    SCODMA006 .u.> SCODMA009 : include

    SCODMA008 .u.> SCODMA010 : include
    SCODMA009 .u.> SCODMA010 : include
}

'actors
actor "Pilot Scientist" as pilot_scientist
actor "Data Scientist" as data_scientist

data_scientist -u- SCODMA006
pilot_scientist -d- SCODMA011


skinparam usecase<<check>> {
    BackgroundColor LightBlue
}

@enduml