@startuml hidalgo2_portal
'left to right direction
skinparam actorStyle awesome

'actors
actor "Portal Admin" as portal_admin
actor "Orchestration Admin" as orchest_admin

portal_admin <|-l- orchest_admin

'packages

package "Portal" << POR >> {
    left to right direction

    usecase SCOPOR001 as "
    Orchestration (Workflow) Management"

    usecase SCOPOR002 as "
    Define HiDALGO2 orchestrations (workflows)"

    usecase SCOPOR003 as "
    Orchestration (Workflow) execution
    "

    usecase SCOPOR004 as "
    Orchestration (workflow) data management
    "

    usecase SCOPOR005 as "
    Orchestration (Workflow) Monitoring
    "

    usecase SCOPOR006 as "
    Data visualization
    "

    usecase SCOPOR007 as "
    3D-visualization of CFD data
    "

    usecase SCOPOR008 as "
    Visualization for data of intermediate workflow steps
    "

    SCOPOR007 -r-|> SCOPOR006
    SCOPOR008 -r-|> SCOPOR006
    
    SCOPOR001 .l.> SCOPOR002 : include
    SCOPOR001 .r.> SCOPOR003 : include
    SCOPOR001 .r.> SCOPOR004 : include
    SCOPOR001 .r.> SCOPOR005 : include

}

actor "Pilot Scientist" as pilot_scientist
actor "Data Scientist" as data_scientist


orchest_admin -d- SCOPOR001
data_scientist -u- SCOPOR006
pilot_scientist -u- SCOPOR001


skinparam usecase<<check>> {
    BackgroundColor LightBlue
}

@enduml