@startuml hidalgo2_hpda_ai
'left to right direction
skinparam actorStyle awesome

'actors
actor "HPDA/AI Scientist" as hpda_scientist

'packages

package "HPDA & AI" << DAAI >> {
    left to right direction


    usecase SCODAAI008 as "
    Data analytics and visualization
    --
    Perform data exploration, sharing, collaboration 
    and visualization. Used by data scientists for 
    carrying out datasets processing and visualization
    "

    usecase SCODAAI001 as "
    Data analytics on notebook frameworks
    "

    usecase SCODAAI002 as "
    Apply AI & ML methods for enhanced simulations
    --
    Apply AI and ML methods to simulations (e.g. feature extraction 
    of input data, parameter estimation).
    "

    usecase SCODAAI003 as "
    Enhance simulations with streaming data
    --
    Enable additional pilot applications to fetch 
    and process streaming data whenever required. 
    "

    usecase SCODAAI004 <<check>> as "
    Component testing and validation
    --
    Implementation partners should be able to test their 
    implementations and in the use case so that the 
    functionality of the component under test can be evaluated.
    "

    usecase SCODAAI005 as "
    Smart assistant for interactive analytical workflows
    --
    Receive suggestions on how to complete analytical tasks 
    that include visual and algorithmic steps. 
    See a visual result preview for analytical workflows, 
    which are suggested based on the data and/or user behavior. 
    Select a preview to activate a ”wizard” for executing that workflow. 
    Make interactive data analysis more accessible to non-experienced users 
    by providing suggestions and guidance.
    "

    usecase SCODAAI006 as "
    Seamless and in-situ data analytics on HPDA servers
    --
    Use and extend data analytics, available on HPDA servers; 
    seamlessly integrate simulation software and data analytics 
    software, avoid time-consuming operations of copying 
    big amounts of data, usable by GSS community.
    "

    usecase SCODAAI007 as "
    Hybrid HPDA|HPC application deployment, running and management
    --
    Support the running and management of applications 
    that have both DA and HPC workflow components. 
    This is used by application providers and developers.
    "

    SCODAAI008 .r.> SCODAAI003: include
    SCODAAI008 .r.> SCODAAI005 : include
    SCODAAI008 .r.> SCODAAI006 : include
    SCODAAI001 -r-|> SCODAAI008

}

actor "Pilot Scientist" as pilot_scientist

hpda_scientist -d- SCODAAI001
hpda_scientist -d- SCODAAI002
hpda_scientist -d- SCODAAI008

pilot_scientist -u- SCODAAI002
pilot_scientist -u- SCODAAI007
pilot_scientist -u- SCODAAI008


skinparam usecase<<check>> {
    BackgroundColor LightBlue
}

@enduml